### ISSUE TITLE
panic when running in release mode

### ISSUE THREAD

**Issue by CrispyPin** [yshui/index_camera_passthrough#6]
When running in release, it panics after showing a few frames from the camera.

```
Found matching device: AMD Radeon RX 6800 XT (RADV NAVI21)
thread 'main' panicked at /home/crispypin/.cargo/git/checkouts/vulkano-0df1d54ea6cf1ce4/d828801/vulkano/src/command_buffer/allocator.rs:440:41:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2831701757eb7b3105eda26a306c2f3a97e2664b/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/2831701757eb7b3105eda26a306c2f3a97e2664b/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/2831701757eb7b3105eda26a306c2f3a97e2664b/library/core/src/panicking.rs:127:5
   3: vulkano::command_buffer::allocator::Entry::allocate
   4: <vulkano::command_buffer::allocator::StandardCommandBufferAllocator as vulkano::command_buffer::allocator::CommandBufferAllocator>::allocate
   5: vulkano::command_buffer::auto::builder::AutoCommandBufferBuilder<L>::begin
   6: index_camera_passthrough::pipeline::submit_cpu_image
   7: index_camera_passthrough::pipeline::Pipeline::run
   8: index_camera_passthrough::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by yshui** [comment]
does it still fail the same way now?

**Comment by CrispyPin** [comment]
It no longer panics, but exits with `VRInputError_IPCError` before even loading in both debug and release. I am using SteamVR 1.25.8.

This is probably caused by something else since going back in the git history doesn't fix it, i'll look into it later

**Comment by CrispyPin** [comment]
It works now, thanks
